# E-Mobile 7 生产环境配置文件
# 支持节假日检测、周末打卡的企业级配置

server:
  base_url: 'http://223.76.229.248:11032'
  auth_url: 'http://223.76.229.248:8999'

schedule:
  # 工作日打卡配置
  workday:
    morning:
      enabled: true
      time_range: ['07:30', '08:00']  # 工作日上班时间范围
      type: 'on'
    evening:
      enabled: true 
      time_range: ['20:00', '21:00']  # 工作日下班时间范围
      type: 'off'
  
  # 周末打卡配置
  weekend:
    morning:
      enabled: true
      time_range: ['08:00', '08:30']  # 周末上班时间范围
      type: 'on'
    evening:
      enabled: true
      time_range: ['17:30', '18:30']  # 周末下班时间范围
      type: 'off'
  
  # 节假日检测（自动跳过法定节假日）
  holiday_check: true
  timezone: 'Asia/Shanghai'

# 用户配置
users:
  - username: 'zhangzhiyuan'  # 请替换为实际用户名
    password: '123456'    # 请替换为实际密码
    user_id: '585'
    display_name: '张志远'
    enabled: true
    location:
      latitude: '30.487572428385416'
      longitude: '114.50522216796875'
      position: '中国武汉市洪山区高新大道772号武汉东湖新技术开发区'
    checkin_rules:
      workday_morning_enabled: true   # 工作日上班打卡
      workday_evening_enabled: true   # 工作日下班打卡
      weekend_morning_enabled: false   # 周末上班打卡
      weekend_evening_enabled: false   # 周末下班打卡

# 监控配置
monitoring:
  health_check_port: 8080
  max_consecutive_failures: 5  # 最大连续失败次数

# 通知配置（可选）
notification:
  enabled: false  # 设为true启用通知
  webhook_url: ''  # Webhook URL（如企业微信、钉钉等）
  email:
    enabled: false
    smtp_server: ''
    username: ''
    password: ''
    to_emails: [] 